# Generated by Django 3.1.3 on 2020-11-19 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201119_2229'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbalance',
            unique_together={('user', 'currency')},
        ),
    ]
