# Generated by Django 3.1.3 on 2020-11-20 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_balances', to='core.currency'),
        ),
    ]
