# Generated by Django 3.1.3 on 2020-11-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201120_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='destination_currency',
        ),
        migrations.RemoveField(
            model_name='order',
            name='origin_currency',
        ),
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_currency_paris', to='core.currency')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_paris', to='core.currency')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='currency_pair',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.currencypair'),
        ),
    ]
