# Generated by Django 3.1.3 on 2020-11-20 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201120_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencypair',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_currency_pairs', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='currencypair',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_currency_pairs', to='core.currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency_pair',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.currencypair'),
            preserve_default=False,
        ),
    ]
