# Generated by Django 3.1.3 on 2020-11-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='original_amount',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=64),
            preserve_default=False,
        ),
    ]
