# Generated by Django 3.1.3 on 2020-11-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201121_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='acronym',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
